### ISSUE TITLE
Just install script uses Perl Regex

### ISSUE THREAD

**Issue by Shad0wRim** [catppuccin/typst#25]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What version(s) of the Typst compiler are you using?

0.11.1

### What version(s) of the Catppuccin package for Typst are you using?

0.1.0

### Describe your problem.

The line ``` version := `grep -m 1 version typst.toml | grep -e '\d.\d.\d' -o` ``` uses `\d` in its regex, which is part of PCRE. This regex should be replaced with `'[0-9]\.[0-9]\.[0-9]'` to make it more portable.

### Attach screenshots.

![image](https://github.com/user-attachments/assets/09d6b52c-c2cd-4925-8d81-fe7ffa971c3d)

### What platform(s) are you seeing the problem on?

WSL2 Ubuntu 22.04

**Comment by TimeTravelPenguin** [comment]
Thanks for posting this issue. I was not aware of this. I will update the scripts to fix that problem.
